apiVersion: v1
kind: Service
metadata:
  name: voting
spec:
  type: NodePort
  ports:
    - name: "voting-service"
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: voting
